################################################################################
#
#   SECTION: Organizations
#
################################################################################
Organizations:

    - &OrdererOrg

        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Impact

        Name: ImpactMSP

        # ID to load the MSP definition as
        ID: ImpactMSP

        MSPDir: crypto-config/peerOrganizations/Impact.el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ImpactMSP.admin', 'ImpactMSP.peer', 'ImpactMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ImpactMSP.admin', 'ImpactMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ImpactMSP.admin')"

        AnchorPeers:
            - Host: peer0.Impact.el-network.com
              Port: 7051

    - &MOPH

        Name: MOPHMSP

        # ID to load the MSP definition as
        ID: MOPHMSP

        MSPDir: crypto-config/peerOrganizations/MOPH.el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('MOPHMSP.admin', 'MOPHMSP.peer', 'MOPHMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('MOPHMSP.admin', 'MOPHMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('MOPHMSP.admin')"

        AnchorPeers:
            - Host: peer0.MOPH.el-network.com
              Port: 7051

    - &BorderControl

        Name: BorderControlMSP

        # ID to load the MSP definition as
        ID: BorderControlMSP

        MSPDir: crypto-config/peerOrganizations/BorderControl.el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BorderControlMSP.admin', 'BorderControlMSP.peer', 'BorderControlMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BorderControlMSP.admin', 'BorderControlMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BorderControlMSP.admin')"

        AnchorPeers:
            - Host: peer0.BorderControl.el-network.com
              Port: 7051

    - &Manufacturer

        Name: ManufacturerMSP

        # ID to load the MSP definition as
        ID: ManufacturerMSP

        MSPDir: crypto-config/peerOrganizations/Manufacturer.el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.peer', 'ManufacturerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin')"

        AnchorPeers:
            - Host: peer0.Manufacturer.el-network.com
              Port: 7051

    - &Hospital

        Name: HospitalMSP

        # ID to load the MSP definition as
        ID: HospitalMSP

        MSPDir: crypto-config/peerOrganizations/Hospital.el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('HospitalMSP.admin', 'HospitalMSP.peer', 'HospitalMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('HospitalMSP.admin', 'HospitalMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('HospitalMSP.admin')"

        AnchorPeers:
            - Host: peer0.Hospital.el-network.com
              Port: 7051

    - &StorageFacility

        Name: StorageFacilityMSP

        # ID to load the MSP definition as
        ID: StorageFacilityMSP

        MSPDir: crypto-config/peerOrganizations/StorageFacility.el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('StorageFacilityMSP.admin', 'StorageFacilityMSP.peer', 'StorageFacilityMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('StorageFacilityMSP.admin', 'StorageFacilityMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('StorageFacilityMSP.admin')"

        AnchorPeers:
            - Host: peer0.StorageFacility.el-network.com
              Port: 7051
    
    - &Donor

        Name: DonorMSP

        # ID to load the MSP definition as
        ID: DonorMSP

        MSPDir: crypto-config/peerOrganizations/Donor.el-network.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DonorMSP.admin', 'DonorMSP.peer', 'DonorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DonorMSP.admin', 'DonorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DonorMSP.admin')"

        AnchorPeers:
            - Host: peer0.Donor.el-network.com
              Port: 7051

################################################################################
#
#   SECTION: Capabilities
#
################################################################################
Capabilities:

    Channel: &ChannelCapabilities

        V1_3: true

    Orderer: &OrdererCapabilities

        V1_1: true

    Application: &ApplicationCapabilities

        V1_3: true

        V1_2: false

        V1_1: false

################################################################################
#
#   SECTION: Application
#
################################################################################
Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities
################################################################################
#
#   SECTION: Orderer
#
################################################################################
Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.el-network.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   SECTION: Channel
#
################################################################################
Channel: &ChannelDefaults

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"

        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   SECTION: Profile
#
################################################################################
Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            ContractConsortium:
                Organizations:
                    - *Impact
                    - *MOPH
                    - *BorderControl
                    - *Manufacturer
                    - *Donor

            DistributionConsortium:
                Organizations:
                    - *Impact
                    - *MOPH
                    - *BorderControl
                    - *Hospital
                    - *StorageFacility
                    - *Donor

    Orderchannel:
        Consortium: ContractConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Impact
                - *MOPH
                - *BorderControl
                - *Manufacturer
                - *Donor
            Capabilities:
                <<: *ApplicationCapabilities
    
    DistributionChannel:
        Consortium: DistributionConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Impact
                - *MOPH
                - *BorderControl
                - *Hospital
                - *StorageFacility
                - *Donor
                
            Capabilities:
                <<: *ApplicationCapabilities

