OrdererOrgs:

  - Name: Orderer
    Domain: el-network.com
    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: impact
    Domain: impact.el-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: MOPH
    Domain: MOPH.el-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: BorderControl
    Domain: BorderControl.el-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Manufacturer
    Domain: Manufacturer.el-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Hospital
    Domain: Hospital.el-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: StorageFacility
    Domain: StorageFacility.el-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Donor
    Domain: Donor.el-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  
